#!/usr/bin/env bash

scap_dir="$HOME/Pictures"
scap_delay="0.1"
scap_compression=3

# sleep 100ms so i3 dmenu won't get in screenshot
sleep $scap_delay

# take screenshot
scrot --format png --compression $scap_compression --file "$scap_dir/"$(date '+%d%m%y_%H%M%S.png')
