---
- name: update all fedora servers
  hosts: servers
  tasks:
    - name: update
      shell: yes | dnf update
      register: update_status
      become: true
    - debug: msg="{{ update_status.stdout }}"
    - name: upgrade
      shell: yes | dnf upgrade
      when: update_status is success
      register: upgrade_status
      become: true
    - debug: msg="{{ upgrade_status.stdout }}"
